
fastlane_version "2.26.1"

default_platform :ios

SLACK_URL = "https://hooks.slack.com/services/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".freeze
FRAMEWORK_NAME = "Pageboy".freeze
REPOSITORY_NAME = "Pageboy".freeze

platform :ios do

  desc "Release new version"
  lane :release do |options|
      target_version = options[:version]
      raise "The version is missed. Use `fastlane release version:{version_number}`.`" if target_version.nil?

      ensure_git_branch
      ensure_git_status_clean
      
      # Increment version
      increment_version_number(xcodeproj: File.join("Sources", "Pageboy.xcodeproj/"), version_number: target_version)  
      
      # Create Carthage framework
      Actions.sh("cd .. && carthage build --no-skip-current && carthage archive #{FRAMEWORK_NAME}")
      framework_binary = File.join(File.expand_path('../..', __FILE__),"#{FRAMEWORK_NAME}.framework.zip")
      raise "No binary found to upload #{framework_binary}" if File.file?(framework_binary) == false

      git_add
      git_commit(path: ".", message: "New release version bump")

      # Create release tag
      push_to_git_remote
      
      set_github_release(
          repository_name: "LootApp/#{REPOSITORY_NAME}",
          api_token: ENV['GITHUB_API_TOKEN'],
          tag_name: target_version,
          upload_assets: [ framework_binary ],
          name: "",
          description: ""
      )

      File.delete(framework_binary)
  end

  desc "Run unit tests and check library"
  lane :test do
    scan(workspace: "Pageboy.xcworkspace", scheme: "Pageboy", clean: true)
    pod_lib_lint(verbose: true)
  end

  desc "Deploy a new version to CocoaPods and GitHub"
  lane :deploy do
    
    podspec = "Pageboy.podspec"
    version = version_get_podspec(path: podspec)

    # Push new Github release
    github_release = set_github_release(
      repository_name: "uias/Pageboy",
      api_token: ENV["GITHUB_TOKEN"],
      name: version,
      tag_name: version,
      description: "#{version} release.",
      commitish: "master"
    )

    # Push spec
    pod_push(allow_warnings: true, verbose: true)

    slack(
      message: "Pageboy v#{version} released!" 
    )
  end
end